name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Check Test
        run: yarn test

      - name: Check linting
        uses: mrdivyansh/eslint-action@v1.0.7

      - name: Check commit message
        uses: wagoid/commitlint-github-action@v3

      - name: Build
        run: yarn build
