name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Check test
        run: yarn test

      - name: Check build
        run: yarn build
        
      - name: Check coveralls
        uses: coverallsapp/github-action@v1.1.2
        with: 
          github-token: uDYfERcLdzdWpc9elz6SoitCtZ3Qx6T8o
